disabled_rules:
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting

opt_in_rules:
  - empty_count
  - empty_string

included:
  - Sources

excluded:
  - .build

line_length:
  warning: 120
  error: 200

type_name:
  min_length: 3
  max_length: 40
