workflows:
  build-foundation-models-tools:
    name: Build and Test FoundationModelsTools
    max_build_duration: 60
    environment:
      xcode: 26.0
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Install SwiftLint
        script: |
          brew install swiftlint
      - name: Run SwiftLint
        script: |
          swiftlint
      - name: Build Swift Package
        script: |
          swift build -c release
